//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Actions/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Game"",
            ""id"": ""46acae58-66d2-48bc-9009-22f12fe39946"",
            ""actions"": [
                {
                    ""name"": ""changeTarget"",
                    ""type"": ""Button"",
                    ""id"": ""bf1354fa-84df-41cd-9172-d9cd74e8f7fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""increaseGameSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""a1c111c8-7897-437c-93b0-98b72e4c7797"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""decreaseGameSpeed"",
                    ""type"": ""Button"",
                    ""id"": ""5d885891-825f-4d4f-a78c-b02b856dd5b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""click"",
                    ""type"": ""Button"",
                    ""id"": ""217fb17a-e7ec-4404-bcee-72f242d08cc9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""clearAction"",
                    ""type"": ""Button"",
                    ""id"": ""a16c03ad-769f-401e-8d6a-448a4950bd92"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""7e8930d3-f647-4658-ba9c-81fb60aef3af"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""42749a8b-00cc-44fc-a6ec-764f7fbc6cf7"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""New control scheme"",
                    ""action"": ""changeTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d34cdc2d-c498-42de-aed2-3b684eb961c9"",
                    ""path"": ""<Keyboard>/numpadPlus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""increaseGameSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f126fd7b-dd06-4a87-a0b2-c4cdaa926594"",
                    ""path"": ""<Keyboard>/rightBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""increaseGameSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a8a8825-902a-4501-8d4c-1c216b238f7f"",
                    ""path"": ""<Keyboard>/numpadMinus"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""decreaseGameSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9090623-419e-4437-99f9-397c05985cbd"",
                    ""path"": ""<Keyboard>/slash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""decreaseGameSpeed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d868bc5f-06f7-4221-bce1-4a0606451e52"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f64b286-fbf8-400c-bd32-75523507d77f"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""clearAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""8c04b6fc-0ff9-400b-bf32-871db5894dec"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fab0ca86-8e70-49d5-b0ab-b2f0a926fcec"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d2935152-d52a-42cd-839a-14fc4aa77444"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""df7c2c14-1cb9-4dba-86fd-b4262d145aa6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""80f27d5b-2fa1-4683-9b9a-b52ca4718e86"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""New control scheme"",
            ""bindingGroup"": ""New control scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Game
        m_Game = asset.FindActionMap("Game", throwIfNotFound: true);
        m_Game_changeTarget = m_Game.FindAction("changeTarget", throwIfNotFound: true);
        m_Game_increaseGameSpeed = m_Game.FindAction("increaseGameSpeed", throwIfNotFound: true);
        m_Game_decreaseGameSpeed = m_Game.FindAction("decreaseGameSpeed", throwIfNotFound: true);
        m_Game_click = m_Game.FindAction("click", throwIfNotFound: true);
        m_Game_clearAction = m_Game.FindAction("clearAction", throwIfNotFound: true);
        m_Game_Move = m_Game.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Game
    private readonly InputActionMap m_Game;
    private List<IGameActions> m_GameActionsCallbackInterfaces = new List<IGameActions>();
    private readonly InputAction m_Game_changeTarget;
    private readonly InputAction m_Game_increaseGameSpeed;
    private readonly InputAction m_Game_decreaseGameSpeed;
    private readonly InputAction m_Game_click;
    private readonly InputAction m_Game_clearAction;
    private readonly InputAction m_Game_Move;
    public struct GameActions
    {
        private @PlayerInput m_Wrapper;
        public GameActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @changeTarget => m_Wrapper.m_Game_changeTarget;
        public InputAction @increaseGameSpeed => m_Wrapper.m_Game_increaseGameSpeed;
        public InputAction @decreaseGameSpeed => m_Wrapper.m_Game_decreaseGameSpeed;
        public InputAction @click => m_Wrapper.m_Game_click;
        public InputAction @clearAction => m_Wrapper.m_Game_clearAction;
        public InputAction @Move => m_Wrapper.m_Game_Move;
        public InputActionMap Get() { return m_Wrapper.m_Game; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameActions set) { return set.Get(); }
        public void AddCallbacks(IGameActions instance)
        {
            if (instance == null || m_Wrapper.m_GameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameActionsCallbackInterfaces.Add(instance);
            @changeTarget.started += instance.OnChangeTarget;
            @changeTarget.performed += instance.OnChangeTarget;
            @changeTarget.canceled += instance.OnChangeTarget;
            @increaseGameSpeed.started += instance.OnIncreaseGameSpeed;
            @increaseGameSpeed.performed += instance.OnIncreaseGameSpeed;
            @increaseGameSpeed.canceled += instance.OnIncreaseGameSpeed;
            @decreaseGameSpeed.started += instance.OnDecreaseGameSpeed;
            @decreaseGameSpeed.performed += instance.OnDecreaseGameSpeed;
            @decreaseGameSpeed.canceled += instance.OnDecreaseGameSpeed;
            @click.started += instance.OnClick;
            @click.performed += instance.OnClick;
            @click.canceled += instance.OnClick;
            @clearAction.started += instance.OnClearAction;
            @clearAction.performed += instance.OnClearAction;
            @clearAction.canceled += instance.OnClearAction;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IGameActions instance)
        {
            @changeTarget.started -= instance.OnChangeTarget;
            @changeTarget.performed -= instance.OnChangeTarget;
            @changeTarget.canceled -= instance.OnChangeTarget;
            @increaseGameSpeed.started -= instance.OnIncreaseGameSpeed;
            @increaseGameSpeed.performed -= instance.OnIncreaseGameSpeed;
            @increaseGameSpeed.canceled -= instance.OnIncreaseGameSpeed;
            @decreaseGameSpeed.started -= instance.OnDecreaseGameSpeed;
            @decreaseGameSpeed.performed -= instance.OnDecreaseGameSpeed;
            @decreaseGameSpeed.canceled -= instance.OnDecreaseGameSpeed;
            @click.started -= instance.OnClick;
            @click.performed -= instance.OnClick;
            @click.canceled -= instance.OnClick;
            @clearAction.started -= instance.OnClearAction;
            @clearAction.performed -= instance.OnClearAction;
            @clearAction.canceled -= instance.OnClearAction;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IGameActions instance)
        {
            if (m_Wrapper.m_GameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameActions instance)
        {
            foreach (var item in m_Wrapper.m_GameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameActions @Game => new GameActions(this);
    private int m_NewcontrolschemeSchemeIndex = -1;
    public InputControlScheme NewcontrolschemeScheme
    {
        get
        {
            if (m_NewcontrolschemeSchemeIndex == -1) m_NewcontrolschemeSchemeIndex = asset.FindControlSchemeIndex("New control scheme");
            return asset.controlSchemes[m_NewcontrolschemeSchemeIndex];
        }
    }
    public interface IGameActions
    {
        void OnChangeTarget(InputAction.CallbackContext context);
        void OnIncreaseGameSpeed(InputAction.CallbackContext context);
        void OnDecreaseGameSpeed(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnClearAction(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
    }
}
